# Generated by Django 4.1.2 on 2022-10-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_review_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchList',
            new_name='watchlist',
        ),
    ]
