# Generated by Django 4.1.2 on 2022-10-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
